# Generated by Django 5.2.12 on 2026-05-29 16:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_learned', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=100)),
                ('custom_definition', models.TextField(blank=True)),
                ('custom_translation', models.CharField(blank=True, max_length=300)),
                ('custom_example', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_entries', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vocabs', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='SRSCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review', models.DateField(default=datetime.date.today)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('mastery_level', models.IntegerField(choices=[(0, '生疏'), (1, '學習中'), (2, '熟悉'), (3, '精通')], default=0)),
                ('user_vocab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='srs_card', to='vocab.uservocab')),
            ],
        ),
        migrations.AddConstraint(
            model_name='uservocab',
            constraint=models.UniqueConstraint(condition=models.Q(('word__isnull', False)), fields=('user', 'word'), name='unique_user_official_word'),
        ),
    ]
