# Generated by Django 5.2.12 on 2026-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_userwordstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocab',
            name='custom_part_of_speech',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uservocab',
            name='custom_phonetic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
