# Generated by Django 5.2.12 on 2026-05-29 17:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_uservocab_custom_part_of_speech_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
                ('user_vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='vocab.uservocab')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
