# Generated by Django 5.2.12 on 2026-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_reviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocab',
            name='ai_mnemonic',
            field=models.TextField(blank=True),
        ),
    ]
