# Generated by Django 5.2.12 on 2026-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_uservocab_ai_mnemonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='deep-space', max_length=50),
        ),
    ]
