# Generated by Django 5.2.12 on 2026-05-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_userprofile_auto_pronounce_userprofile_daily_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pronunciation_pref',
            field=models.CharField(choices=[('US', '美音'), ('UK', '英音')], default='US', max_length=10),
        ),
    ]
