# Generated by Django 5.2.12 on 2026-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_userprofile_pronunciation_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_border_style',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_gold_badge',
            field=models.BooleanField(default=False),
        ),
    ]
