# Generated by Django 5.2.12 on 2026-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_userprofile_card_border_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_effect',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenges_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_badge',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
