# Generated by Django 5.2.12 on 2026-06-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_userprofile_background_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unlocked_items',
            field=models.TextField(default='theme:deep-space,theme:aurora,border:default,effect:none'),
        ),
    ]
