# Generated by Django 5.2.12 on 2026-05-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100, unique=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('source', models.CharField(default='TOEIC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Phonetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=100)),
                ('notation_type', models.CharField(choices=[('IPA', 'IPA'), ('KK', 'KK')], default='IPA', max_length=5)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonetics', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('n', 'Noun'), ('v', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('prep', 'Preposition'), ('conj', 'Conjunction'), ('pron', 'Pronoun'), ('phrase', 'Phrase')], max_length=10)),
                ('definition', models.TextField()),
                ('translation', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='words.word')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('translation', models.CharField(blank=True, max_length=500)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.wordsense')),
            ],
        ),
    ]
