# Generated by Django 5.2.12 on 2026-05-31 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_category_word_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=250)),
                ('missing_part', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=250)),
                ('distractors', models.JSONField(default=list)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collocations', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordConfusable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True)),
                ('confusable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusable_by', to='words.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusables', to='words.word')),
            ],
            options={
                'unique_together': {('word', 'confusable')},
            },
        ),
    ]
